Repository openshift/template-service-broker, pull requests merged in 2019-07, with the labels that each got.

#2 Add dockerfiles
  images/Dockerfile
  images/Dockerfile.rhel
Labels: approved, lgtm, size/S

#3 Bump to fix verify-deps
  glide.lock
  vendor/github.com/docker/distribution/contrib/docker-integration/malevolent-certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver-oauth/certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver/certs/ca.pem
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/seq_test.go
  vendor/github.com/google/uuid/sql_test.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/uuid_test.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/scheduler/nodeenv/admission_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector_test.go
  vendor/k8s.io/kubernetes/third_party/etcd.BUILD
Labels: size/XXL

#6 Add current owners
  OWNERS
Labels: approved, lgtm, size/XS
